customer:
  address: 123 Main St
  city: Test City
  country: Test Country
  name: Test Company
  zip: '12345'
internationalization:
  currency_format: EUR
  default_language: en
  supported_languages:
  - en
  - de
  - fr
offer:
  date: '2025-02-16'
  number: OFFER-2025-02-16
  validity:
    de: 30 Tage
    en: 30 days
sales:
  email: john.doe@example.com
  name: John Doe
  phone: +1 234 567 890
settings:
  base_path: /Users/luxus/projects/OfferDocGenerator/cli_test/test_project
  folders:
    common: ./common
    output: ./output
    products: ./products
    templates: ./templates
  output_prefix: DOC-
